
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      spec:
        containers:
          - name: web-app
            image: nginx:latest
            ports:
              - containerPort: 80
            resources:
              limits:
                cpu: "1"
                memory: "512Mi"
              requests:
                cpu: "500m"
                memory: "256Mi" 